export const baseSeo = {
  keywords: [
    "Clínica de saúde",
    "Bem-estar",
    "Longevidade",
    "Emagrecimento",
    "Hipertrofia",
    "Reposição hormonal",
    "Nutrição",
    "Medicina esportiva",
    "Medicina preventiva",
    "Medicina integrativa",
    "Alimentação saudável",
    "Saúde",
    "Estética",
    "São Paulo",
    "Tratamentos personalizados",
    "Nutrologia",
    "Envelhecimento saudável",
    "Modulação hormonal",
    "Saúde e qualidade de vida",
    "Equilíbrio nutricional",
    "Claudio Mutti",
    "Dr. Claudio Mutti",
    "Dr Claudio Mutti",
    "amauryjr",
    "Amaury Jr",
    "Mutti",
    "Marcelo Lima",
  ],
};
