export const baseSeo = {
  keywords: [
  "Clínica de saúde",
    "Clínica de saúde em São Paulo",
    "Clínica de saúde em São Paulo SP",
    "Médico em São Paulo",
    "Bem-estar",
    "Longevidade",
    "Saúde e bem-estar",
    "Saúde e longevidade",
    "Emagrecimento",
    "Emagrecimento saudável",
    "Hipertrofia",
    "Hipertrofia muscular",
    "Reposição hormonal",
    "Reposição hormonal masculina",
    "Reposição hormonal feminina",
    "Nutrição",
    "Nutrição esportiva",
    "Nutrição funcional",
    "Nutrição e saúde",
    "Medicina esportiva",
    "Medicina esportiva em São Paulo",
    "Medicina esportiva em São Paulo SP",
    "Medicina esportiva em São Paulo capital",
    "Medicina esportiva em São Paulo zona sul",
    "Medicina preventiva",
    "Medicina preventiva em São Paulo",
    "Medicina preventiva em São Paulo SP",
    "Medicina preventiva em São Paulo capital",
    "Medicina integrativa",
    "Alimentação saudável",
    "Saúde",
    "Estética",
    "São Paulo",
    "Tratamentos personalizados",
    "Nutrologia",
    "Envelhecimento saudável",
    "Modulação hormonal",
    "Saúde e qualidade de vida",
    "Equilíbrio nutricional",
    "Claudio Mutti",
    "Dr. Claudio Mutti",
    "Dr Claudio Mutti",
    "amauryjr",
    "Amaury Jr",
    "Mutti",
    "Marcelo Lima",
  ],
};
